sudo: required

services:
  - docker

language: bash

before_script:
  - sh ./scripts/install_rancher.sh

branches:
  only:
    - master
    - /^v(\d+\.)?(\d+\.)?\d+(-\w+)?$/

script: sh ./scripts/travis_build.sh
