sudo: required

services:
  - docker

language: bash

env:
  - CLUSTER_NAME=main REGION="europe-west3" PROJECT_ID="payment-server-reloaded" REGISTRY_HOSTNAME="eu.gcr.io"

branches:
  only:
    - gcp-migration
    - /^v(\d+\.)?(\d+\.)?\d+(-\w+)?$/

before_script:
  - ${TRAVIS_BUILD_DIR}/scripts/install_rancher.sh
  - ${TRAVIS_BUILD_DIR}/scripts/install_gcloud.sh

script:
  - ${TRAVIS_BUILD_DIR}/scripts/travis-build.sh
  - ${TRAVIS_BUILD_DIR}/scripts/travis-gcp-build.sh

deploy:
  - provider: script
    skip_cleanup: true
    # deploy to kube dev namespace
    script: ${TRAVIS_BUILD_DIR}/k8s/gcp-dev-deploy.sh
    on:
      branch: gcp-migration

