version: '2'
services:
  dashboard:
    image: hub.mblb.net/payment-sdk-dashboard-open:latest
    labels:
      service.name: carrier
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
