name: CI

on: [push, pull_request]
env:
  REGISTRY: hub.mblb.net/payment-sdk-dashboard-open
  CLUSTER_NAME: main
  REGION: europe-west3
  PROJECT_ID: payment-server-reloaded
  REGISTRY_HOSTNAME: eu.gcr.io
  IMAGE_NAME: payment-dashboard

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image - GCP
        run: docker build -t eu.gcr.io/payment-server-reloaded/payment-dashboard:commit-${{ github.sha }} .
      - uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      - uses: actions/gcloud/cli@master
        with:
          args: |
            gcloud config set project ${PROJECT_ID}
            gcloud auth configure-docker --quiet
      - name: Tag Docker Images
        run: |
          if ${{ github.head_ref != ''}}; then
            docker tag eu.gcr.io/payment-server-reloaded/payment-dashboard:commit-${{ github.sha }} eu.gcr.io/payment-server-reloaded/payment-dashboard:pr-${{ github.head_ref }}
          fi
          if ${{ endsWith(github.ref, 'master') }}; then
            docker tag eu.gcr.io/payment-server-reloaded/payment-dashboard:commit-${{ github.sha }} eu.gcr.io/payment-server-reloaded/payment-dashboard:latest
          fi
          docker tag eu.gcr.io/payment-server-reloaded/payment-dashboard:commit-${{ github.sha }} eu.gcr.io/payment-server-reloaded/payment-dashboard:commit-${{ github.head_ref }}
      - name: Push Docker Images
        run: docker push eu.gcr.io/payment-server-reloaded/payment-dashboard:commit-${{ github.sha }}
  deploy-dev:
    if: startsWith(github.ref, 'master')
    name: Deploy Dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: azure/k8s-actions/setup-kubectl@master
        with:
          version: '1.11.0'
      - name: Run srcipt
        run: cd ${GITHUB_WORKSPACE}/payment-sdk-dashboard && ./k8s/gcp-dev-deploy.sh
  deploy-demo:
    if: contains(github.head_ref, 'demo')
    name: Deploy Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: azure/k8s-actions/setup-kubectl@master
        with:
          version: '1.11.0'
      - name: Run script
        run: cd ${GITHUB_WORKSPACE}/payment-sdk-dashboard && ./k8s/gcp-demo-deploy.sh
